### ISSUE TITLE
请教：关于1：n分值区分度的问题

### ISSUE THREAD

**Issue by bleakie** [shoutOutYangJie/Face_Recognition_using_pytorch#1]
您好，我在进行1：n的时候，top1和top2的分值区分度不大，请问这种问题在训练的时候如何解决呢？

**Comment by shoutOutYangJie** [comment]
sorry, I don't understand what you mean. if you mean that top1 denotes face with most probability and top2 denotes the face with sub-max probability,  i would tell you that arc loss doesn't care about it during the training. Arc loss tries to minimize the vectors' angle to  achieve recognition. if two feature vectors' angle is lower than a threshold, it means that two corresponding face images belong to one person.

**Comment by bleakie** [comment]
如何针对性的对1：n的场景进行模型的训练呢？现在的方法都是对1：1的情境下进行，在1：n的时候并不能取得更优秀的效果，感谢您的回复

**Comment by huangzhenjie** [comment]
@bleakie 感觉用arc loss ,top1和top2还是有区分度的啊,效果比triplet loss好
